name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        environment: AzureUSGovernment
        creds:  ${{ secrets.AZURE_CREDENTIALS  }}
      
    - name: Azure CLI Action
      uses: Azure/cli@v1.0.7
      with:
        inlineScript: az account set --subscription 3bd54f98-8de8-4dd8-bfe0-acf49e7cb725
    
    - uses: actions/checkout@v3
   
    - name: Docker Images Build And Push
      uses: azure/docker-login@v1
      with:
        login-server: ghrefacr.azurecr.us
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --file SampleApp/Dockerfile -t ghrefacr.azurecr.us/sampleapp:${{github.run_number}} -t ghrefacr.azurecr.us/sampleapp:latest
        docker push ghrefacr.azurecr.us/sampleapp:${{github.run_number}}
        docker push ghrefacr.azurecr.us/sampleapp:latest
    
    
        
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1.1.3'
      with:
          resource-group: ghref-rg
          dns-name-label: sampleapp
          image: ghrefacr.azurecr.us/sampleapp:${{github.run_number}}
          registry-login-server: ghrefacr.azurecr.us
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: sampleapp-aci
          location: 'USGov Virginia'
       
