name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file SampleApp/Dockerfile --tag sampleapp:latest
    
    - uses: elstudio/action-install-azure-cli@v1
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds:  ${{ secrets.AZURE_CREDENTIALS  }}
    
    - name: Deploy to Azure Container Instances
      uses: Azure/aci-deploy@v1
      with:
        resource-group: ghref-rg
        dns-name-label: sampleapp
        image: sampleapp:latest
        ip-address: Public
        location: USGovVirginia
        memory: 1.5
        name: sampleapp-aci
       
